[package]
name = "lvrs"
version = "0.1.0"
edition = "2021"

[lib]
name = "lv"
path = "src/lib.rs"

[[bin]]
name = "hello"
path = "src/bin/hello.rs"

[dependencies]
actix = "0.13.0"
actix-web = "4.3.1"
actix-web-actors = "4.2.0"
serde_json = "1.0"
uuid = { version = "1", features = ["v4"] }
